language: bash
services: docker
before_install:
  - echo "We are in the Docker folder!"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push tiagosp13/mysql_api-spring-docker-aws;
    docker push tiagosp13/api-spring-docker-aws;
  on:
    branch: master
notifications:
  email: false
