version: '3.4'
services:
  db:
    image: tiagosp13/mysql_api-spring-docker-aws
    container_name: mysql_api-spring-docker-aws
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: marketplace
    ports:
      - "3308:3306"
    networks:
      - network
  api-spring-docker-aws:
    image: tiagosp13/api-spring-docker-aws
    container_name: api-spring-docker-aws
    restart: always
    build: ./
    working_dir: /api-spring-docker-aws
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - .:/api-spring-docker-aws
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - network
networks:
  network:
    driver: bridge
